### ISSUE TITLE
Problem showing certain metrics

### ISSUE THREAD

**Issue by knobz12** [braiins/farm-monitor#10]
Hi. I recently installed braiins os+ on two antminer s9. I have farm monitor running on a raspberry pi and get some of the monitoring but not values like temperature. The temperature values are displayed in the metrics for the miners, but not in the farm monitor.

![miners](https://user-images.githubusercontent.com/15209910/232361622-ccc774a8-98f9-46c3-bba6-caf1836ccf8c.PNG)
![temp](https://user-images.githubusercontent.com/15209910/232361626-f60bbb36-e0a0-4102-a107-4eaf44f9fb34.PNG)

**Comment by vitficl** [comment]
Hi @knobz12, thanks for pointing out the issue. Check out the latest release. The temp metric for S9 is there. In previous version it was just accidently filterd out in from Prometheus data.
