### ISSUE TITLE
23.12 not detecting miners

### ISSUE THREAD

**Issue by papampi** [braiins/farm-monitor#16]
Since last update there is a problem and it wont detect most of my miners 

23.05 Screenshot:

![Screenshot from 2023-12-19 11-26-27](https://github.com/braiins/farm-monitor/assets/1108483/4133f69e-ddd1-45a5-93d2-83d30fd50680)

23.12 Screenshot:

![Screenshot from 2023-12-19 11-30-12](https://github.com/braiins/farm-monitor/assets/1108483/c32a50b8-1136-4611-9ff8-88968f83a4e5)

**Comment by vitficl** [comment]
fixed in 24.03, thanks for reporting this issue
